### ISSUE TITLE
Windows support

### ISSUE THREAD

**Issue by zchrissirhcz** [fbcotter/py3nvml#15]
Hi, thanks for creating this tool.
Is there any plan supporing Windows platform?

**Comment by fbcotter** [comment]
It should be able to currently but I have not tested it on windows as I don't have access to a windows machine. The crux of the interface is just loading the NVIDIA library file. For linux this is `libnvidia-ml.so.1` and for windows this should be `nvml.dll`. What error do you get when you try use it? 

If you're keen to problem solve, you could try have a look at [this function](https://github.com/fbcotter/py3nvml/blob/008fee73e30d729b77cde0d8c54d01c8f1d8b566/py3nvml/py3nvml.py#L1104), and see if you can see a dll file in the listed paths there:

**Comment by zchrissirhcz** [comment]
Hi, thanks for response.
On my Windows 10 machine, using Python3.7.4, installed by `pip install py3nvml`.

Then in git-bash, it outputs:
```
$ py3smi
Traceback (most recent call last):
  File "E:/soft/Miniconda3/Scripts/py3smi", line 10, in <module>
    import pwd
ModuleNotFoundError: No module named 'pwd'
```

But `pip install pwd` failed. Any idea?
