### ISSUE TITLE
Question: Retrieve Peak GPU memory usage

### ISSUE THREAD

**Issue by patrickvonplaten** [fbcotter/py3nvml#16]
Hello @fbcotter, 

Thanks a lot for the great library! 
Do you know how one could retrieve the peak GPU memory usage of a process?

**Comment by fbcotter** [comment]
Hi @patrickvonplaten sorry I didn't get a notification about your question! I'm sure you'd have figured something out by now, but if you want it to be access programmatically, you could spin up a monitoring process that queries the gpu state regularly using py3nvml and keeps track of the peaks. 

If you just want to see the peaks maybe something like [nvtop](https://github.com/Syllo/nvtop) is better. Or even simpler would be `watch -n 0.5 py3smi` (if you have py3nvml installed or `watch -n 0.5 nvidia-smi` if you don't)
