### ISSUE TITLE
module 'string' has no attribute 'join'

### ISSUE THREAD

**Issue by ikfj** [fbcotter/py3nvml#2]
Hi,
When I tried to do e.g. print(nvmlDeviceGetName(h)) I got the following error.

```
File "/home/**/build/nvidia-ml-py/src/py3nvml/py3nvml/py3nvml.py", line 399, in __str__
    return self.__class__.__name__ + "(" + string.join(result, ", ") + ")"
AttributeError: module 'string' has no attribute 'join'
```

I'm sorry but I'm blind to Python and I have no idea. Could you investigate it?

**Comment by fbcotter** [comment]
The nvmlDeviceGetName() function shouldn't call the code that was causing the above error. Are you sure that was what caused it?

However, there is still a bug, if you call print(nvmlDeviceGetMemoryInfo(handle)), then it should throw the same error.

I've pushed a fix up to master. Try pulling and see if that works.

**Comment by ikfj** [comment]
Hi fbcoder, you are right, what I tried was print(nvmlDeviceGetUtilizationRates(handle)).
And yes, now it works well. Thank you for your effort!
