### ISSUE TITLE
0.2.7 version not available on github

### ISSUE THREAD

**Issue by tim77** [fbcotter/py3nvml#22]
0.2.7 available on [PyPI](https://pypi.org/project/py3nvml/), but not tagged on github. Please publish new version on github since it also contain `docs/`.

**Comment by fbcotter** [comment]
Oops, sorry Tim. Good spot. I'll bump the version and make sure it's tagged

**Comment by tim77** [comment]
@fbcotter hello. Sorry for disturb, but would be nice to fix this minor issue before f36 release. Some apps, like GWE [requires](https://bugzilla.redhat.com/show_bug.cgi?id=2071946#c2) new 0.2.7 version.

**Comment by fbcotter** [comment]
Done. I didn't end up bumping the version but have made the tag and code available on github

**Comment by tim77** [comment]
Thank you!
